In [2]:
import torch
import numpy as np

In [6]:
x = torch.empty(5 ,3)
x

tensor([[9.2755e-39, 9.1837e-39, 9.3674e-39],
        [1.0745e-38, 1.0653e-38, 9.5510e-39],
        [1.0561e-38, 1.0194e-38, 1.1112e-38],
        [1.0561e-38, 9.9184e-39, 1.0653e-38],
        [4.1327e-39, 1.0194e-38, 1.0469e-38]])

In [8]:
x = torch.rand(5 ,3)
x

tensor([[0.6540, 0.8913, 0.6331],
        [0.7564, 0.0710, 0.9725],
        [0.0192, 0.4931, 0.2600],
        [0.1166, 0.6427, 0.1724],
        [0.4993, 0.0433, 0.4891]])

In [10]:
x = torch.zeros(5 ,3 ,dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [11]:
torch.tensor([1.213,3])

tensor([1.2130, 3.0000])

In [14]:
x = x.new_ones(5 ,3 ,dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [16]:
x = torch.randn_like(x ,dtype=torch.float)
x

tensor([[ 1.1512, -0.4338,  1.0763],
        [ 0.2501, -0.9572,  1.8593],
        [ 0.5169,  0.3557,  0.4488],
        [ 0.2120,  1.4868, -0.1292],
        [-0.0171, -1.9215, -0.0213]])

In [18]:
x = torch.arange(0 , 19 ,2)
x

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
x = torch.linspace(0 , 10, 4)
x

tensor([ 0.0000,  3.3333,  6.6667, 10.0000])

In [23]:
x = torch.FloatTensor([5 ,6 ,7])
print(x)
print(x.dtype)

tensor([5., 6., 7.])
torch.float32


In [25]:
torch.manual_seed(42)
x = torch.rand(2 ,3)
print(x)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


In [26]:
torch.manual_seed(42)
x = torch.rand(2 ,3)
print(x)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])
